// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21

#define SYS_paintWindow   22
#define SYS_registWindow 23
#define SYS_sendMessage 24
#define SYS_getMessage 25
#define SYS_setTimer 26
#define SYS_destroyWindow 27
#define SYS_killTimer 28
#define SYS_initStringFigure 29
#define SYS_getStringFigure 30
#define SYS_getTime 31
#define SYS_getDate 32
#define SYS_setCursor 33
#define SYS_flushRect 34
#define SYS_resetWindow 35
#define SYS_getWindowInfo 36
#define SYS_directPaintWindow 37
#define SYS_setSampleRate 38
#define SYS_writeSoundBuf 39
#define SYS_pause 40
#define SYS_wavSectionPlay 41
#define SYS_beginMP3Decode 42
#define SYS_waitForMP3Decode 43
#define SYS_endMP3Decode 44
#define SYS_getCoreBuf 45